import enum


class WorkMainCategory(enum.Enum):
    CAREGIVING_NURSING_MEDICAL = "CAREGIVING_NURSING_MEDICAL"
    CONSTRUCTION_CIVIL_ENGINEERING_LABOR = "CONSTRUCTION_CIVIL_ENGINEERING_LABOR"
    COOKING_SERVING = "COOKING_SERVING"
    CULTURE_LEISURE_LIFESTYLE = "CULTURE_LEISURE_LIFESTYLE"
    DISTRIBUTION_SALES = "DISTRIBUTION_SALES"
    DRIVING_DELIVERY_LOGISTICS = "DRIVING_DELIVERY_LOGISTICS"
    EDUCATION_INSTRUCTION = "EDUCATION_INSTRUCTION"
    OFFICE_ACCOUNTING_IT = "OFFICE_ACCOUNTING_IT"
    PRODUCTION_TECHNICAL = "PRODUCTION_TECHNICAL"
    SALES_CONSULTING = "SALES_CONSULTING"
    SERVICE = "SERVICE"
